"""Loopback proxy that signs Agent CLI model requests with Job delegation identity."""

from __future__ import annotations

from contextlib import ExitStack
import hashlib
import json
import logging
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from threading import Lock, Thread
from typing import Any
from urllib.parse import urlparse
from weakref import WeakValueDictionary
import requests

from openmontage.invocation_store import InvocationRequestConflictError, ModelInvocationStore
from tools.dofe.delegation import DelegatedModelCredential


_HOP_HEADERS = {
    "authorization",
    "connection",
    "content-length",
    "host",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
}
_MAX_REQUEST_BYTES = 32 * 1024 * 1024
_MAX_CACHED_RESPONSE_BYTES = 8 * 1024 * 1024
_LOGGER = logging.getLogger("openmontage.delegation_proxy")
# Logical-call identity policy (deliberate, audited — not a heuristic).
#
# Codex is the only executor whose OpenAI-compatible traffic crosses this proxy,
# and it does not emit an OpenMontage-specific logical-call header. Its own
# X-Request-Id / Idempotency-Key are regenerated per ephemeral session, so
# honoring them would give every crash-restart a fresh invocation id and defeat
# replay recovery. With no caller-supplied stable identity available, the proxy
# must pick one of two failure modes and apply it consistently:
#
#   * wrong-merge — two genuinely distinct same-content calls within one
#     stage/attempt collapse onto one invocation and the second replays the
#     first cached response; vs.
#   * double-bill — every call is a new invocation, so a crash-restart re-bills.
#
# This proxy deliberately chooses dedup: when the logical-call header is absent
# the stable content fingerprint below is the replay key, so a same-content
# crash-replay recovers the cached response (no re-bill) and genuinely different
# content gets a new invocation. The accepted, documented limitation is the
# wrong-merge case above — bounded to a single stage/attempt and rare in
# practice because Codex rarely issues byte-identical Responses calls twice in
# one stage. Callers that CAN supply a stable identity (e.g. native tool paths)
# set X-OpenMontage-Logical-Call-Id, which is then used strictly and never
# falls back to the fingerprint.
#
# A true per-call identity (stage + attempt + call_sequence) is the only way to
# fully close the wrong-merge case, but it must originate on the caller side:
# this proxy cannot tell a retransmitted call from a distinct same-content call
# by bytes alone. Codex owns its HTTP client, so the question is whether the
# model-provider config OpenMontage sets via
# pipeline_executor._configure_agent_command_for_delegation can carry a value
# that varies per call. Verified against codex-cli 0.146.0 (the pinned revision,
# inspected in the shipped binary): ModelProviderInfo exposes only
# base_url / query_params / env_key / wire_api / auth flags — there is NO
# per-request header field (http_headers / env_http_headers exist only for HTTP
# MCP servers, resolved once "executor-side", i.e. static-per-process), and no
# model-request-level Idempotency-Key (the idempotency strings in the binary are
# billing/credits internals and MCP tool annotations). Every knob OpenMontage
# can turn is therefore static-per-invocation, so any identity derived from it
# would collapse every call in a stage onto one id — strictly worse than the
# content fingerprint, which at least distinguishes different-content calls. The
# real fix is blocked on a Codex capability (per-call header interpolation or a
# stable per-call Idempotency-Key) that is not available today. Until then,
# every replay this proxy serves is logged with replay_key_source =
# "logical_call_id" (the safe case) or "content_fingerprint" (the wrong-merge-
# prone case), so the limitation is observable and auditable rather than silent.
_LOGICAL_CALL_HEADERS = (
    "X-OpenMontage-Logical-Call-Id",
)


def _request_fingerprint(method: str, path: str, body: bytes | None, content_type: str) -> str:
    normalized_body = body or b""
    if normalized_body and "json" in content_type.lower():
        try:
            parsed = json.loads(normalized_body)
            if _is_responses_path(path) and isinstance(parsed, dict):
                # Volatile fields are stripped so the fingerprint is a pure
                # function of the durable request content — the replay key
                # described in the logical-call identity policy above.
                # prompt_cache_key / client_metadata (cache key, thread/turn ids,
                # turn timestamps) are regenerated by Codex per ephemeral
                # session; leaving them in would change the fingerprint across a
                # crash-restart and a same-content replay would mint a new
                # invocation instead of recovering the cached response.
                parsed = {
                    key: value
                    for key, value in parsed.items()
                    if key not in {"prompt_cache_key", "client_metadata"}
                }
            normalized_body = json.dumps(
                parsed,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        except (UnicodeDecodeError, json.JSONDecodeError):
            pass
    digest = hashlib.sha256()
    digest.update(method.upper().encode("ascii"))
    digest.update(b"\n")
    digest.update(path.encode("utf-8"))
    digest.update(b"\n")
    digest.update(normalized_body)
    return digest.hexdigest()


def _is_responses_path(path: str) -> bool:
    return urlparse(path).path.rstrip("/").endswith("/responses")


def _send_response(
    handler: BaseHTTPRequestHandler,
    status_code: int,
    headers: dict[str, str],
    body: bytes,
) -> None:
    handler.send_response(status_code)
    for key, value in headers.items():
        if key.lower() not in _HOP_HEADERS:
            handler.send_header(key, value)
    handler.send_header("Connection", "close")
    handler.end_headers()
    handler.wfile.write(body)


class DelegationSigningProxy:
    def __init__(
        self,
        credential: DelegatedModelCredential,
        *,
        invocation_store: ModelInvocationStore | None = None,
        job_id: str | None = None,
        stage: str | None = None,
        stage_attempt: int = 1,
    ) -> None:
        self.credential = credential
        self.invocation_store = invocation_store
        self.job_id = job_id or credential.external_job_id
        self.stage = stage or credential.pipeline_stage
        self.stage_attempt = stage_attempt
        parsed = urlparse(credential.models_base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ValueError("Delegated models base URL is invalid")
        self._upstream_origin = f"{parsed.scheme}://{parsed.netloc}"
        self._upstream_prefix = parsed.path.rstrip("/")
        self._server: ThreadingHTTPServer | None = None
        self._thread: Thread | None = None
        self._invocation_locks_guard = Lock()
        self._invocation_locks: WeakValueDictionary[str, Lock] = WeakValueDictionary()

    def __enter__(self) -> "DelegationSigningProxy":
        proxy = self

        class Handler(BaseHTTPRequestHandler):
            def do_GET(self) -> None:  # noqa: N802
                proxy._forward(self)

            def do_POST(self) -> None:  # noqa: N802
                proxy._forward(self)

            def do_DELETE(self) -> None:  # noqa: N802
                proxy._forward(self)

            def log_message(self, _format: str, *_args: Any) -> None:
                return None

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self._thread = Thread(target=self._server.serve_forever, name="openmontage-model-proxy", daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *_args: object) -> None:
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()
        if self._thread is not None:
            self._thread.join(timeout=2)

    @property
    def base_url(self) -> str:
        if self._server is None:
            raise RuntimeError("Delegation signing proxy has not started")
        host, port = self._server.server_address
        return f"http://{host}:{port}{self._upstream_prefix}"

    def _forward(self, handler: BaseHTTPRequestHandler) -> None:
        response_cached = False
        response_started = False
        invocation_lock: Lock | None = None
        lock_stack = ExitStack()
        upstream: requests.Response | None = None
        try:
            length = int(handler.headers.get("Content-Length", "0"))
            if length < 0 or length > _MAX_REQUEST_BYTES:
                handler.send_error(413)
                return
            body = handler.rfile.read(length) if length else None
            fingerprint = _request_fingerprint(
                handler.command,
                handler.path,
                body,
                handler.headers.get("Content-Type", ""),
            )
            logical_call_id = next(
                (
                    value
                    for name in _LOGICAL_CALL_HEADERS
                    if (value := handler.headers.get(name, "").strip())
                ),
                "",
            )
            seed = logical_call_id or fingerprint
            replay_key_source = (
                "logical_call_id" if logical_call_id else "content_fingerprint"
            )
            if self.invocation_store is None:
                invocation_id = "om-" + hashlib.sha256(
                    f"{self.credential.external_job_id}\n{self.credential.pipeline_stage}\n{seed}".encode()
                ).hexdigest()[:32]
            else:
                record = self.invocation_store.get_or_create(
                    job_id=self.job_id,
                    stage=self.stage,
                    attempt=self.stage_attempt,
                    request_id=seed,
                    request_fingerprint=fingerprint,
                )
                invocation_id = record.model_invocation_id
                invocation_lock = self._get_invocation_lock(invocation_id)
                invocation_lock.acquire()
                lock_stack.callback(invocation_lock.release)
                lock_stack.enter_context(
                    self.invocation_store.invocation_lock(invocation_id)
                )
                record = self.invocation_store.get_or_create(
                    job_id=self.job_id,
                    stage=self.stage,
                    attempt=self.stage_attempt,
                    request_id=seed,
                    request_fingerprint=fingerprint,
                )
                cached = self.invocation_store.get_cached_response(invocation_id)
                if cached is not None:
                    response_cached = True
                    self._log_replay(
                        invocation_id,
                        replay_key_source=replay_key_source,
                        outcome="replayed_cached",
                    )
                    _send_response(handler, cached.status_code, cached.headers, cached.body)
                    return
                if record.status == "succeeded":
                    response_cached = True
                    self._log_replay(
                        invocation_id,
                        replay_key_source=replay_key_source,
                        outcome="not_replayable_409",
                    )
                    _send_response(
                        handler,
                        409,
                        {"Content-Type": "application/json"},
                        json.dumps(
                            {
                                "error": {
                                    "code": "OPENMONTAGE_RESPONSE_NOT_REPLAYABLE",
                                    "message": "The successful model response exceeded the replay cache limit",
                                }
                            },
                            separators=(",", ":"),
                        ).encode("utf-8"),
                    )
                    return
                self.invocation_store.mark(invocation_id, "in_flight")
            headers = {
                key: value
                for key, value in handler.headers.items()
                if key.lower() not in _HOP_HEADERS
            }
            headers["Authorization"] = f"Bearer {self.credential.api_key}"
            headers.update(self.credential.signed_headers(model_invocation_id=invocation_id))
            upstream = requests.request(
                handler.command,
                f"{self._upstream_origin}{handler.path}",
                headers=headers,
                data=body,
                stream=True,
                allow_redirects=False,
                timeout=(10, 3600),
            )
            response_headers = {
                key: value
                for key, value in upstream.headers.items()
                if key.lower() not in _HOP_HEADERS
            }
            if upstream.headers.get("Content-Type", "").lower().split(";", 1)[0].strip() == (
                "text/event-stream"
            ):
                handler.send_response(upstream.status_code)
                for key, value in response_headers.items():
                    handler.send_header(key, value)
                handler.send_header("Connection", "close")
                handler.end_headers()
                response_started = True
                response_body = bytearray()
                can_buffer = True
                downstream_open = True
                while True:
                    chunk = upstream.raw.read1(64 * 1024, decode_content=False)
                    if not chunk:
                        break
                    if can_buffer:
                        if len(response_body) + len(chunk) <= _MAX_CACHED_RESPONSE_BYTES:
                            response_body.extend(chunk)
                        else:
                            can_buffer = False
                            response_body.clear()
                    if downstream_open:
                        try:
                            handler.wfile.write(chunk)
                            handler.wfile.flush()
                        except OSError:
                            downstream_open = False
                if self.invocation_store is not None:
                    if can_buffer:
                        self.invocation_store.save_response(
                            invocation_id,
                            status_code=upstream.status_code,
                            headers=response_headers,
                            body=bytes(response_body),
                        )
                        response_cached = True
                    else:
                        self.invocation_store.mark(
                            invocation_id,
                            "succeeded" if upstream.status_code < 400 else "failed",
                        )
                return
            content_length = upstream.headers.get("Content-Length", "")
            can_buffer = True
            if content_length.isdigit() and int(content_length) > _MAX_CACHED_RESPONSE_BYTES:
                can_buffer = False
            if can_buffer:
                response_body = upstream.raw.read(
                    _MAX_CACHED_RESPONSE_BYTES + 1,
                    decode_content=False,
                )
                can_buffer = len(response_body) <= _MAX_CACHED_RESPONSE_BYTES
            else:
                response_body = b""
            if can_buffer:
                if self.invocation_store is not None:
                    self.invocation_store.save_response(
                        invocation_id,
                        status_code=upstream.status_code,
                        headers=response_headers,
                        body=response_body,
                    )
                    response_cached = True
                _send_response(handler, upstream.status_code, response_headers, response_body)
            else:
                handler.send_response(upstream.status_code)
                for key, value in response_headers.items():
                    handler.send_header(key, value)
                handler.send_header("Connection", "close")
                handler.end_headers()
                if response_body:
                    handler.wfile.write(response_body)
                for chunk in upstream.raw.stream(64 * 1024, decode_content=False):
                    handler.wfile.write(chunk)
            if self.invocation_store is not None and not can_buffer:
                self.invocation_store.mark(
                    invocation_id,
                    "succeeded" if upstream.status_code < 400 else "failed",
                )
        except InvocationRequestConflictError as exc:
            handler.send_error(409, str(exc))
        except Exception:
            if (
                self.invocation_store is not None
                and "invocation_id" in locals()
                and not response_cached
            ):
                self.invocation_store.mark(invocation_id, "unknown")
            if response_started:
                handler.close_connection = True
            else:
                handler.send_error(502)
        finally:
            if upstream is not None:
                upstream.close()
            lock_stack.close()

    def _get_invocation_lock(self, invocation_id: str) -> Lock:
        with self._invocation_locks_guard:
            lock = self._invocation_locks.get(invocation_id)
            if lock is None:
                lock = Lock()
                self._invocation_locks[invocation_id] = lock
            return lock

    def _log_replay(
        self,
        invocation_id: str,
        *,
        replay_key_source: str,
        outcome: str,
    ) -> None:
        """Emit a structured record when a cached/deduped response is served.

        replay_key_source distinguishes the safe dedup case (a caller-supplied
        logical call id) from the wrong-merge-prone fallback (content
        fingerprint), so the documented limitation is observable rather than
        silent. See the logical-call identity policy above.
        """
        _LOGGER.info(
            "openmontage delegation replay served",
            extra={
                "event": "replay_served",
                "outcome": outcome,
                "job_id": self.job_id,
                "stage": self.stage,
                "attempt": self.stage_attempt,
                "invocation_id": invocation_id,
                "replay_key_source": replay_key_source,
            },
        )
